version: '2.4'

services:

  database:
    image: postgres
    container_name: protheus_database
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
<<<<<<< HEAD
      - ./docker/mssql/entrypoint.sh:/entrypoint.sh
      - ./docker/mssql/dbinit.sh:/dbinit.sh
      - ./docker/mssql/dbinit.sql:/dbinit.sql
    ports: 
      - ${DB_PORT}:1433
    mem_limit: 3000m
=======
      - pg_data:${PG_DATA}
>>>>>>> e699f4017c6c52b7c46168f0f9df9e32019623ec

  license:
    image: docker.totvs.io/dcp/license
    container_name: protheus_license
    
  dbaccess:
    build: ./docker/totvs-dbaccess-docker
    container_name: protheus_dbaccess
    ports:
      - 7890:7890
    environment:
      - DB_TYPE=${DB_TYPE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    depends_on: 
      - database
      - license

  appserver:
    build: ./docker/totvs-appserver-docker
    container_name: protheus_appserver
    ports:
      - 9999:9999
    user: root
    environment:
      - DBACCESS_SERVER=${DBACCESS_SERVER}
      - DBACCESS_ALIAS=${DBACCESS_ALIAS}
      - DBACCESS_PORT=${DBACCESS_PORT}
    volumes:
      - ${PROTHEUS_DATA_PATH}:/totvs12/protheus_data
      - ${PROTHEUS_APO_PATH}:/totvs12/protheus/apo
    depends_on: 
      - dbaccess
      - license

volumes:
  pg_data: {}